from django.contrib.gis.db import models


# all the models/class created here are autogenerated using the LayerMapping Utility
class JabongaFloodHazard(models.Model):
    gridcode = models.IntegerField()
    datetime = models.CharField(max_length=50)
    geom = models.MultiPolygonField(srid=32651, null=True, blank=True)
    objects = models.GeoManager()

    def __unicode__(self):
        return "{0} {1}".format("Date: " + unicode(self.datetime), " -- Gridcode: " + unicode(self.gridcode))
        #return self.datetime


class ProjectMunicipalities(models.Model):
    iso = models.CharField(max_length=3)
    name_0 = models.CharField(max_length=75)
    id_1 = models.IntegerField()
    name_1 = models.CharField(max_length=75)
    id_2 = models.IntegerField()
    name_2 = models.CharField(max_length=75)
    type_2 = models.CharField(max_length=50)
    engtype_2 = models.CharField(max_length=50)
    name = models.CharField(max_length=50)
    layer = models.CharField(max_length=100)
    geom = models.MultiPolygonField(srid=4326, null=True, blank=True)
    objects = models.GeoManager()

    def __unicode__(self):
        return self.name


class ProjectBarangays(models.Model):
    fid_field = models.IntegerField(null=True, blank=True)
    bdry_name = models.CharField(max_length=50, null=True, blank=True)
    area_sq_m = models.FloatField(null=True, blank=True)
    brgy_name = models.CharField(max_length=50)
    area_calcu = models.FloatField(null=True, blank=True)
    municipali = models.CharField(max_length=50)
    province = models.CharField(max_length=50)
    geom = models.MultiPolygonField(srid=4326, null=True, blank=True)
    objects = models.GeoManager()

    def __unicode__(self):
        return self.brgy_name


class JabongaBuilding(models.Model):
    #id = models.IntegerField()
    bldg_name = models.CharField(max_length=50)
    #height = models.FloatField()
    #code = models.CharField(max_length=5)
    #block_name = models.CharField(max_length=50)
    brgy_locat = models.CharField(max_length=50)
    municipali = models.CharField(max_length=50)
    province = models.CharField(max_length=50)
    bldg_type = models.CharField(max_length=50)
    geom = models.MultiPolygonField(srid=32651, null=True, blank=True)
    objects = models.GeoManager()


####FLOOD EVENTS###
class RiverBasin(models.Model):
    desc = models.CharField(max_length=100)

    def __unicode__(self):
        return unicode(self.desc)


class FloodEvent(models.Model):
    desc = models.CharField(max_length=25)
    river_basin = models.ForeignKey(RiverBasin)
    tbl_name = models.CharField(max_length=50)
    flood_maps = models.CharField(max_length=50)

    def __unicode__(self):
        #return "{0} {1}".format("Desc: " + unicode(self.desc), " River Basin: " + unicode(self.river_basin))
        return unicode(self.desc)


#####STATIC MODEL####
class AgatonCbr(models.Model):
    hazard = models.CharField(max_length=16)
    geom = models.MultiPolygonField(srid=4326, null=True, blank=True)
    objects = models.GeoManager()

    def __unicode__(self):
        return unicode(self.hazard)


class SeniangCbr(models.Model):
    gridcode = models.IntegerField()
    geom = models.MultiPolygonField(srid=4326, null=True, blank=True)
    objects = models.GeoManager()

    def __unicode__(self):
        return unicode(self.hazard)


class CbrTwoYear(models.Model):
    gridcode = models.IntegerField()
    geom = models.MultiPolygonField(srid=4326, null=True, blank=True)
    objects = models.GeoManager()

    def __unicode__(self):
        return unicode(self.hazard)


class CbrFiveYear(models.Model):
    gridcode = models.IntegerField()
    geom = models.MultiPolygonField(srid=4326, null=True, blank=True)
    objects = models.GeoManager()

    def __unicode__(self):
        return unicode(self.hazard)


class CbrTenYear(models.Model):
    gridcode = models.IntegerField()
    geom = models.MultiPolygonField(srid=4326, null=True, blank=True)
    objects = models.GeoManager()

    def __unicode__(self):
        return unicode(self.hazard)


class CbrTwentyFiveYear(models.Model):
    gridcode = models.IntegerField()
    geom = models.MultiPolygonField(srid=4326, null=True, blank=True)
    objects = models.GeoManager()

    def __unicode__(self):
        return unicode(self.hazard)


class CbrFiftyYear(models.Model):
    gridcode = models.IntegerField()
    geom = models.MultiPolygonField(srid=4326, null=True, blank=True)
    objects = models.GeoManager()

    def __unicode__(self):
        return unicode(self.hazard)


class CbrHundredYear(models.Model):
    gridcode = models.IntegerField()
    geom = models.MultiPolygonField(srid=4326, null=True, blank=True)
    objects = models.GeoManager()

    def __unicode__(self):
        return unicode(self.hazard)


##### MAINIT-TUBAY #####


class MainitTubay2Year(models.Model):
    #id = models.IntegerField()
    grid_code = models.IntegerField()
    #shape_leng = models.FloatField()
    #shape_area = models.FloatField()
    #hazard = models.CharField(max_length=30)
    geom = models.MultiPolygonField(srid=32651)
    objects = models.GeoManager()

    def __unicode__(self):
        return unicode(self.grid_code)


class MainitTubay5Year(models.Model):
    #id = models.IntegerField()
    grid_code = models.IntegerField()
    #shape_leng = models.FloatField()
    #shape_area = models.FloatField()
    #hazard = models.CharField(max_length=30)
    geom = models.MultiPolygonField(srid=32651)
    objects = models.GeoManager()

    def __unicode__(self):
        return unicode(self.grid_code)


class MainitTubay10Year(models.Model):
    #id = models.IntegerField()
    grid_code = models.IntegerField()
    #shape_leng = models.FloatField()
    #shape_area = models.FloatField()
    #hazard = models.CharField(max_length=30)
    geom = models.MultiPolygonField(srid=32651)
    objects = models.GeoManager()

    def __unicode__(self):
        return unicode(self.grid_code)


class MainitTubay25Year(models.Model):
    #id = models.IntegerField()
    grid_code = models.IntegerField()
    #shape_leng = models.FloatField()
    #shape_area = models.FloatField()
    #hazard = models.CharField(max_length=30)
    geom = models.MultiPolygonField(srid=32651)
    objects = models.GeoManager()

    def __unicode__(self):
        return unicode(self.grid_code)


class MainitTubay50Year(models.Model):
    #id = models.IntegerField()
    grid_code = models.IntegerField()
    #shape_leng = models.FloatField()
    #shape_area = models.FloatField()
    #hazard = models.CharField(max_length=30)
    geom = models.MultiPolygonField(srid=32651)
    objects = models.GeoManager()

    def __unicode__(self):
        return unicode(self.grid_code)


class MainitTubay100Year(models.Model):
    #id = models.IntegerField()
    grid_code = models.IntegerField()
    #shape_leng = models.FloatField()
    #shape_area = models.FloatField()
    #hazard = models.CharField(max_length=30)
    geom = models.MultiPolygonField(srid=32651)
    objects = models.GeoManager()

    def __unicode__(self):
        return unicode(self.grid_code)


class MainitTubayAgaton(models.Model):
    #id = models.IntegerField()
    grid_code = models.IntegerField()
    #shape_leng = models.FloatField()
    #shape_area = models.FloatField()
    #hazard = models.CharField(max_length=30)
    geom = models.MultiPolygonField(srid=32651)
    objects = models.GeoManager()

    def __unicode__(self):
        return unicode(self.grid_code)


class MainitTubaySeniang(models.Model):
    #id = models.IntegerField()
    grid_code = models.IntegerField()
    #shape_leng = models.FloatField()
    #shape_area = models.FloatField()
    #hazard = models.CharField(max_length=30)
    geom = models.MultiPolygonField(srid=32651)
    objects = models.GeoManager()

    def __unicode__(self):
        return unicode(self.grid_code)


class MainitTubayBldg(models.Model):
    #id = models.IntegerField()
    bldg_name = models.CharField(max_length=50)
    #height = models.FloatField()
    code = models.CharField(max_length=5)
    bldg_type = models.CharField(max_length=50)
    brgy_locat = models.CharField(max_length=50)
    municipali = models.CharField(max_length=50)
    province = models.CharField(max_length=50)
    geom = models.MultiPolygonField(srid=32651)
    objects = models.GeoManager()

    def __unicode__(self):
        return unicode(self.bldg_name)


class BuildingType(models.Model):
    code = models.CharField(max_length=3)
    description = models.CharField(max_length=50)

    def __unicode__(self):
        return unicode(self.code)


class RiverBasinMunicipality(models.Model):
    river_basin = models.ForeignKey(RiverBasin)
    municipality = models.CharField(max_length=100)
    province = models.CharField(max_length=100)

    def __unicode__(self):
        return unicode(self.municipality)


class CabadbaranBldg(models.Model):
    #id = models.IntegerField()
    bldg_name = models.CharField(max_length=100)
    #height = models.FloatField()
    code = models.CharField(max_length=25)
    #block_name = models.CharField(max_length=75)
    bldg_type = models.CharField(max_length=50)
    brgy_locat = models.CharField(max_length=50)
    municipali = models.CharField(max_length=50)
    province = models.CharField(max_length=50)
    geom = models.MultiPolygonField(srid=32651)
    objects = models.GeoManager()

    def __unicode__(self):
        return unicode(self.bldg_name)


class CabadbaranFloodHazard(models.Model):
    #id = models.IntegerField()
    gridcode = models.IntegerField()
    #hazard = models.CharField(max_length=6)
    date_field = models.CharField(max_length=50)
    geom = models.MultiPolygonField(srid=32651)
    objects = models.GeoManager()

    def __unicode__(self):
        return unicode(self.gridcode)


class WaterLevelStation(models.Model):
    no = models.FloatField()
    station_na = models.CharField(max_length=254)
    river = models.CharField(max_length=254)
    barangay = models.CharField(max_length=254)
    mun = models.CharField(max_length=254)
    province = models.CharField(max_length=254)
    latitude = models.FloatField()
    longitude = models.FloatField()
    remarks = models.CharField(max_length=254)
    access = models.CharField(max_length=254)
    condition = models.CharField(max_length=254)
    geom = models.MultiPointField(srid=32651)
    objects = models.GeoManager()


#####TAGO RIVER BASIN####
class TagoBldg(models.Model):
    #id = models.IntegerField()
    bldg_name = models.CharField(max_length=50)
    #height = models.FloatField()
    code = models.CharField(max_length=10)
    bldg_type = models.CharField(max_length=50)
    brgy_locat = models.CharField(max_length=50)
    municipali = models.CharField(max_length=50)
    province = models.CharField(max_length=50)
    geom = models.MultiPolygonField(srid=32651)
    objects = models.GeoManager()

    def __unicode__(self):
        return unicode(self.bldg_name)


class Tago2Year(models.Model):
    #id = models.IntegerField()
    gridcode = models.IntegerField()
    #shape_leng = models.FloatField()
    #shape_area = models.FloatField()
    #hazard = models.CharField(max_length=30)
    geom = models.MultiPolygonField(srid=32651)
    objects = models.GeoManager()

    def __unicode__(self):
        return unicode(self.gridcode)


class Tago5Year(models.Model):
    #id = models.IntegerField()
    gridcode = models.IntegerField()
    #shape_leng = models.FloatField()
    #shape_area = models.FloatField()
    #hazard = models.CharField(max_length=30)
    geom = models.MultiPolygonField(srid=32651)
    objects = models.GeoManager()

    def __unicode__(self):
        return unicode(self.gridcode)


class Tago10Year(models.Model):
    #id = models.IntegerField()
    gridcode = models.IntegerField()
    #shape_leng = models.FloatField()
    #shape_area = models.FloatField()
    #hazard = models.CharField(max_length=30)
    geom = models.MultiPolygonField(srid=32651)
    objects = models.GeoManager()

    def __unicode__(self):
        return unicode(self.gridcode)


class Tago25Year(models.Model):
    #id = models.IntegerField()
    gridcode = models.IntegerField()
    #shape_leng = models.FloatField()
    #shape_area = models.FloatField()
    #hazard = models.CharField(max_length=30)
    geom = models.MultiPolygonField(srid=32651)
    objects = models.GeoManager()

    def __unicode__(self):
        return unicode(self.gridcode)


class Tago50Year(models.Model):
    #id = models.IntegerField()
    gridcode = models.IntegerField()
    #shape_leng = models.FloatField()
    #shape_area = models.FloatField()
    #hazard = models.CharField(max_length=30)
    geom = models.MultiPolygonField(srid=32651)
    objects = models.GeoManager()

    def __unicode__(self):
        return unicode(self.gridcode)


class Tago100Year(models.Model):
    #id = models.IntegerField()
    gridcode = models.IntegerField()
    #shape_leng = models.FloatField()
    #shape_area = models.FloatField()
    #hazard = models.CharField(max_length=30)
    geom = models.MultiPolygonField(srid=32651)
    objects = models.GeoManager()

    def __unicode__(self):
        return unicode(self.gridcode)


class TagoAgaton(models.Model):
    #id = models.IntegerField()
    gridcode = models.IntegerField()
    #shape_leng = models.FloatField()
    #shape_area = models.FloatField()
    #hazard = models.CharField(max_length=30)
    geom = models.MultiPolygonField(srid=32651)
    objects = models.GeoManager()

    def __unicode__(self):
        return unicode(self.gridcode)


class TagoSeniang(models.Model):
    #id = models.IntegerField()
    gridcode = models.IntegerField()
    #shape_leng = models.FloatField()
    #shape_area = models.FloatField()
    #hazard = models.CharField(max_length=30)
    geom = models.MultiPolygonField(srid=32651)
    objects = models.GeoManager()

    def __unicode__(self):
        return unicode(self.gridcode)


##Tandag River Basin##
class TandagAgaton(models.Model):
    #id = models.IntegerField()
    gridcode = models.IntegerField()
    #shape_leng = models.FloatField()
    #shape_area = models.FloatField()
    #hazard = models.CharField(max_length=30)
    geom = models.MultiPolygonField(srid=32651)
    objects = models.GeoManager()

    def __unicode__(self):
        return unicode(self.gridcode)


class TandagSeniang(models.Model):
    #id = models.IntegerField()
    gridcode = models.IntegerField()
    #shape_leng = models.FloatField()
    #shape_area = models.FloatField()
    #hazard = models.CharField(max_length=30)
    geom = models.MultiPolygonField(srid=32651)
    objects = models.GeoManager()

    def __unicode__(self):
        return unicode(self.gridcode)


class Tandag100Year(models.Model):
    #id = models.IntegerField()
    gridcode = models.IntegerField()
    #shape_leng = models.FloatField()
    #shape_area = models.FloatField()
    #hazard = models.CharField(max_length=30)
    geom = models.MultiPolygonField(srid=32651)
    objects = models.GeoManager()

    def __unicode__(self):
        return unicode(self.gridcode)


class Tandag50Year(models.Model):
    #id = models.IntegerField()
    gridcode = models.IntegerField()
    #shape_leng = models.FloatField()
    #shape_area = models.FloatField()
    #hazard = models.CharField(max_length=30)
    geom = models.MultiPolygonField(srid=32651)
    objects = models.GeoManager()

    def __unicode__(self):
        return unicode(self.gridcode)


class Tandag25Year(models.Model):
    #id = models.IntegerField()
    gridcode = models.IntegerField()
    #shape_leng = models.FloatField()
    #shape_area = models.FloatField()
    #hazard = models.CharField(max_length=30)
    geom = models.MultiPolygonField(srid=32651)
    objects = models.GeoManager()

    def __unicode__(self):
        return unicode(self.gridcode)


class Tandag10Year(models.Model):
    #id = models.IntegerField()
    gridcode = models.IntegerField()
    #shape_leng = models.FloatField()
    #shape_area = models.FloatField()
    #hazard = models.CharField(max_length=30)
    geom = models.MultiPolygonField(srid=32651)
    objects = models.GeoManager()

    def __unicode__(self):
        return unicode(self.gridcode)


class Tandag5Year(models.Model):
    #id = models.IntegerField()
    gridcode = models.IntegerField()
    #shape_leng = models.FloatField()
    #shape_area = models.FloatField()
    #hazard = models.CharField(max_length=30)
    geom = models.MultiPolygonField(srid=32651)
    objects = models.GeoManager()

    def __unicode__(self):
        return unicode(self.gridcode)


class Tandag2Year(models.Model):
    #id = models.IntegerField()
    gridcode = models.IntegerField()
    #shape_leng = models.FloatField()
    #shape_area = models.FloatField()
    #hazard = models.CharField(max_length=30)
    geom = models.MultiPolygonField(srid=32651)
    objects = models.GeoManager()

    def __unicode__(self):
        return unicode(self.gridcode)


class TandagBldg(models.Model):
    #id = models.IntegerField()
    bldg_name = models.CharField(max_length=50)
    #height = models.FloatField()
    code = models.CharField(max_length=10)
    bldg_type = models.CharField(max_length=50)
    brgy_locat = models.CharField(max_length=50)
    municipali = models.CharField(max_length=50)
    province = models.CharField(max_length=50)
    geom = models.MultiPolygonField(srid=32651)
    objects = models.GeoManager()

    def __unicode__(self):
        return unicode(self.bldg_name)


###HUBO-OTIEZA##
class HuboOtiezaBldg(models.Model):
    #id = models.IntegerField()
    bldg_name = models.CharField(max_length=50)
    code = models.CharField(max_length=50)
    bldg_type = models.CharField(max_length=50)
    brgy_locat = models.CharField(max_length=50)
    municipali = models.CharField(max_length=50)
    province = models.CharField(max_length=50)
    geom = models.MultiPolygonField(srid=32651)
    objects = models.GeoManager()


class HuboOtieza100Year(models.Model):
    #id = models.IntegerField()
    gridcode = models.IntegerField()
    #shape_leng = models.FloatField()
    #shape_area = models.FloatField()
    #hazard = models.CharField(max_length=30)
    geom = models.MultiPolygonField(srid=32651)
    objects = models.GeoManager()

    def __unicode__(self):
        return unicode(self.gridcode)


class HuboOtieza50Year(models.Model):
    #id = models.IntegerField()
    gridcode = models.IntegerField()
    #shape_leng = models.FloatField()
    #shape_area = models.FloatField()
    #hazard = models.CharField(max_length=30)
    geom = models.MultiPolygonField(srid=32651)
    objects = models.GeoManager()

    def __unicode__(self):
        return unicode(self.gridcode)


class HuboOtieza25Year(models.Model):
    #id = models.IntegerField()
    gridcode = models.IntegerField()
    #shape_leng = models.FloatField()
    #shape_area = models.FloatField()
    #hazard = models.CharField(max_length=30)
    geom = models.MultiPolygonField(srid=32651)
    objects = models.GeoManager()

    def __unicode__(self):
        return unicode(self.gridcode)


class HuboOtieza10Year(models.Model):
    #id = models.IntegerField()
    gridcode = models.IntegerField()
    #shape_leng = models.FloatField()
    #shape_area = models.FloatField()
    #hazard = models.CharField(max_length=30)
    geom = models.MultiPolygonField(srid=32651)
    objects = models.GeoManager()

    def __unicode__(self):
        return unicode(self.gridcode)


class HuboOtieza5Year(models.Model):
    #id = models.IntegerField()
    gridcode = models.IntegerField()
    #shape_leng = models.FloatField()
    #shape_area = models.FloatField()
    #hazard = models.CharField(max_length=30)
    geom = models.MultiPolygonField(srid=32651)
    objects = models.GeoManager()

    def __unicode__(self):
        return unicode(self.gridcode)


class HuboOtieza2Year(models.Model):
    #id = models.IntegerField()
    gridcode = models.IntegerField()
    #shape_leng = models.FloatField()
    #shape_area = models.FloatField()
    #hazard = models.CharField(max_length=30)
    geom = models.MultiPolygonField(srid=32651)
    objects = models.GeoManager()

    def __unicode__(self):
        return unicode(self.gridcode)


class HuboOtiezaAgaton(models.Model):
    #id = models.IntegerField()
    gridcode = models.IntegerField()
    #shape_leng = models.FloatField()
    #shape_area = models.FloatField()
    #hazard = models.CharField(max_length=30)
    geom = models.MultiPolygonField(srid=32651)
    objects = models.GeoManager()

    def __unicode__(self):
        return unicode(self.gridcode)


class HuboOtiezaSeniang(models.Model):
    #id = models.IntegerField()
    gridcode = models.IntegerField()
    #shape_leng = models.FloatField()
    #shape_area = models.FloatField()
    #hazard = models.CharField(max_length=30)
    geom = models.MultiPolygonField(srid=32651)
    objects = models.GeoManager()

    def __unicode__(self):
        return unicode(self.gridcode)


##hinatuan
class HinatuanBldg(models.Model):
    #id = models.IntegerField()
    bldg_name = models.CharField(max_length=50)
    code = models.CharField(max_length=50)
    bldg_type = models.CharField(max_length=50)
    brgy_locat = models.CharField(max_length=50)
    municipali = models.CharField(max_length=50)
    province = models.CharField(max_length=50)
    geom = models.MultiPolygonField(srid=32651)
    objects = models.GeoManager()

    def __unicode__(self):
        return unicode(self.bldg_name)


class Hinatuan100Year(models.Model):
    #id = models.IntegerField()
    gridcode = models.IntegerField()
    #shape_leng = models.FloatField()
    #shape_area = models.FloatField()
    #hazard = models.CharField(max_length=30)
    geom = models.MultiPolygonField(srid=32651)
    objects = models.GeoManager()

    def __unicode__(self):
        return unicode(self.gridcode)


class Hinatuan50Year(models.Model):
    #id = models.IntegerField()
    gridcode = models.IntegerField()
    #shape_leng = models.FloatField()
    #shape_area = models.FloatField()
    #hazard = models.CharField(max_length=30)
    geom = models.MultiPolygonField(srid=32651)
    objects = models.GeoManager()

    def __unicode__(self):
        return unicode(self.gridcode)


class Hinatuan25Year(models.Model):
    #id = models.IntegerField()
    gridcode = models.IntegerField()
    #shape_leng = models.FloatField()
    #shape_area = models.FloatField()
    #hazard = models.CharField(max_length=30)
    geom = models.MultiPolygonField(srid=32651)
    objects = models.GeoManager()

    def __unicode__(self):
        return unicode(self.gridcode)


class Hinatuan10Year(models.Model):
    #id = models.IntegerField()
    gridcode = models.IntegerField()
    #shape_leng = models.FloatField()
    #shape_area = models.FloatField()
    #hazard = models.CharField(max_length=30)
    geom = models.MultiPolygonField(srid=32651)
    objects = models.GeoManager()

    def __unicode__(self):
        return unicode(self.gridcode)


class Hinatuan5Year(models.Model):
    #id = models.IntegerField()
    gridcode = models.IntegerField()
    #shape_leng = models.FloatField()
    #shape_area = models.FloatField()
    #hazard = models.CharField(max_length=30)
    geom = models.MultiPolygonField(srid=32651)
    objects = models.GeoManager()

    def __unicode__(self):
        return unicode(self.gridcode)


class Hinatuan2Year(models.Model):
    #id = models.IntegerField()
    gridcode = models.IntegerField()
    #shape_leng = models.FloatField()
    #shape_area = models.FloatField()
    #hazard = models.CharField(max_length=30)
    geom = models.MultiPolygonField(srid=32651)
    objects = models.GeoManager()

    def __unicode__(self):
        return unicode(self.gridcode)


class HinatuanAgaton(models.Model):
    #id = models.IntegerField()
    gridcode = models.IntegerField()
    #shape_leng = models.FloatField()
    #shape_area = models.FloatField()
    #hazard = models.CharField(max_length=30)
    geom = models.MultiPolygonField(srid=32651)
    objects = models.GeoManager()

    def __unicode__(self):
        return unicode(self.gridcode)


class HinatuanSeniang(models.Model):
    #id = models.IntegerField()
    gridcode = models.IntegerField()
    #shape_leng = models.FloatField()
    #shape_area = models.FloatField()
    #hazard = models.CharField(max_length=30)
    geom = models.MultiPolygonField(srid=32651)
    objects = models.GeoManager()

    def __unicode__(self):
        return unicode(self.gridcode)


###BISLIG
class BisligBldg(models.Model):
    #id = models.IntegerField()
    bldg_name = models.CharField(max_length=50)
    code = models.CharField(max_length=50)
    bldg_type = models.CharField(max_length=50)
    brgy_locat = models.CharField(max_length=50)
    municipali = models.CharField(max_length=50)
    province = models.CharField(max_length=50)
    geom = models.MultiPolygonField(srid=32651)
    objects = models.GeoManager()

    def __unicode__(self):
        return unicode(self.bldg_name)


class BisligSeniang(models.Model):
    #id = models.IntegerField()
    gridcode = models.IntegerField()
    #shape_leng = models.FloatField()
    #shape_area = models.FloatField()
    #hazard = models.CharField(max_length=30)
    geom = models.MultiPolygonField(srid=32651)
    objects = models.GeoManager()

    def __unicode__(self):
        return unicode(self.gridcode)


class BisligAgaton(models.Model):
    #id = models.IntegerField()
    gridcode = models.IntegerField()
    #shape_leng = models.FloatField()
    #shape_area = models.FloatField()
    #hazard = models.CharField(max_length=30)
    geom = models.MultiPolygonField(srid=32651)
    objects = models.GeoManager()

    def __unicode__(self):
        return unicode(self.gridcode)


class Bislig100Year(models.Model):
    #id = models.IntegerField()
    gridcode = models.IntegerField()
    #shape_leng = models.FloatField()
    #shape_area = models.FloatField()
    #hazard = models.CharField(max_length=30)
    geom = models.MultiPolygonField(srid=32651)
    objects = models.GeoManager()

    def __unicode__(self):
        return unicode(self.gridcode)


class Bislig50Year(models.Model):
    #id = models.IntegerField()
    gridcode = models.IntegerField()
    #shape_leng = models.FloatField()
    #shape_area = models.FloatField()
    #hazard = models.CharField(max_length=30)
    geom = models.MultiPolygonField(srid=32651)
    objects = models.GeoManager()

    def __unicode__(self):
        return unicode(self.gridcode)


class Bislig25Year(models.Model):
    #id = models.IntegerField()
    gridcode = models.IntegerField()
    #shape_leng = models.FloatField()
    #shape_area = models.FloatField()
    #hazard = models.CharField(max_length=30)
    geom = models.MultiPolygonField(srid=32651)
    objects = models.GeoManager()

    def __unicode__(self):
        return unicode(self.gridcode)


class Bislig10Year(models.Model):
    #id = models.IntegerField()
    gridcode = models.IntegerField()
    #shape_leng = models.FloatField()
    #shape_area = models.FloatField()
    #hazard = models.CharField(max_length=30)
    geom = models.MultiPolygonField(srid=32651)
    objects = models.GeoManager()

    def __unicode__(self):
        return unicode(self.gridcode)


class Bislig5Year(models.Model):
    #id = models.IntegerField()
    gridcode = models.IntegerField()
    #shape_leng = models.FloatField()
    #shape_area = models.FloatField()
    #hazard = models.CharField(max_length=30)
    geom = models.MultiPolygonField(srid=32651)
    objects = models.GeoManager()

    def __unicode__(self):
        return unicode(self.gridcode)


class Bislig2Year(models.Model):
    #id = models.IntegerField()
    gridcode = models.IntegerField()
    #shape_leng = models.FloatField()
    #shape_area = models.FloatField()
    #hazard = models.CharField(max_length=30)
    geom = models.MultiPolygonField(srid=32651)
    objects = models.GeoManager()

    def __unicode__(self):
        return unicode(self.gridcode)


class SeniangCBR1(models.Model):
    #id = models.IntegerField()
    depth = models.FloatField()
    arrival = models.FloatField()
    duration = models.FloatField()
    recession = models.FloatField()
    percent = models.FloatField()
    velocity = models.FloatField()
    geom = models.MultiPolygonField(srid=32651)
    objects = models.GeoManager()


#Surigao River Basin Flood Hazard Maps
class Surigao2Year(models.Model):
    #id = models.IntegerField()
    gridcode = models.IntegerField()
    #shape_leng = models.FloatField()
    #shape_area = models.FloatField()
    #hazard = models.CharField(max_length=30)
    geom = models.MultiPolygonField(srid=32651)
    objects = models.GeoManager()

    def __unicode__(self):
        return unicode(self.gridcode)


class Surigao5Year(models.Model):
    #id = models.IntegerField()
    gridcode = models.IntegerField()
    #shape_leng = models.FloatField()
    #shape_area = models.FloatField()
    #hazard = models.CharField(max_length=30)
    geom = models.MultiPolygonField(srid=32651)
    objects = models.GeoManager()

    def __unicode__(self):
        return unicode(self.gridcode)


class Surigao10Year(models.Model):
    #id = models.IntegerField()
    gridcode = models.IntegerField()
    #shape_leng = models.FloatField()
    #shape_area = models.FloatField()
    #hazard = models.CharField(max_length=30)
    geom = models.MultiPolygonField(srid=32651)
    objects = models.GeoManager()

    def __unicode__(self):
        return unicode(self.gridcode)


class Surigao25Year(models.Model):
    #id = models.IntegerField()
    gridcode = models.IntegerField()
    #shape_leng = models.FloatField()
    #shape_area = models.FloatField()
    #hazard = models.CharField(max_length=30)
    geom = models.MultiPolygonField(srid=32651)
    objects = models.GeoManager()

    def __unicode__(self):
        return unicode(self.gridcode)


class Surigao50Year(models.Model):
    #id = models.IntegerField()
    gridcode = models.IntegerField()
    #shape_leng = models.FloatField()
    #shape_area = models.FloatField()
    #hazard = models.CharField(max_length=30)
    geom = models.MultiPolygonField(srid=32651)
    objects = models.GeoManager()

    def __unicode__(self):
        return unicode(self.gridcode)


class Surigao100Year(models.Model):
    #id = models.IntegerField()
    gridcode = models.IntegerField()
    #shape_leng = models.FloatField()
    #shape_area = models.FloatField()
    #hazard = models.CharField(max_length=30)
    geom = models.MultiPolygonField(srid=32651)
    objects = models.GeoManager()

    def __unicode__(self):
        return unicode(self.gridcode)


class SurigaoAgaton(models.Model):
    #id = models.IntegerField()
    gridcode = models.IntegerField()
    #shape_leng = models.FloatField()
    #shape_area = models.FloatField()
    #hazard = models.CharField(max_length=30)
    geom = models.MultiPolygonField(srid=32651)
    objects = models.GeoManager()

    def __unicode__(self):
        return unicode(self.gridcode)


class SurigaoSeniang(models.Model):
    #id = models.IntegerField()
    gridcode = models.IntegerField()
    #shape_leng = models.FloatField()
    #shape_area = models.FloatField()
    #hazard = models.CharField(max_length=30)
    geom = models.MultiPolygonField(srid=32651)
    objects = models.GeoManager()

    def __unicode__(self):
        return unicode(self.gridcode)


#Magallanes Flood Hazard Maps
class Magallanes2Year(models.Model):
    #id = models.IntegerField()
    gridcode = models.IntegerField()
    #shape_leng = models.FloatField()
    #shape_area = models.FloatField()
    #hazard = models.CharField(max_length=30)
    geom = models.MultiPolygonField(srid=32651)
    objects = models.GeoManager()

    def __unicode__(self):
        return unicode(self.gridcode)


class Magallanes5Year(models.Model):
    #id = models.IntegerField()
    gridcode = models.IntegerField()
    #shape_leng = models.FloatField()
    #shape_area = models.FloatField()
    #hazard = models.CharField(max_length=30)
    geom = models.MultiPolygonField(srid=32651)
    objects = models.GeoManager()

    def __unicode__(self):
        return unicode(self.gridcode)


class Magallanes10Year(models.Model):
    #id = models.IntegerField()
    gridcode = models.IntegerField()
    #shape_leng = models.FloatField()
    #shape_area = models.FloatField()
    #hazard = models.CharField(max_length=30)
    geom = models.MultiPolygonField(srid=32651)
    objects = models.GeoManager()

    def __unicode__(self):
        return unicode(self.gridcode)


class Magallanes25Year(models.Model):
    #id = models.IntegerField()
    gridcode = models.IntegerField()
    #shape_leng = models.FloatField()
    #shape_area = models.FloatField()
    #hazard = models.CharField(max_length=30)
    geom = models.MultiPolygonField(srid=32651)
    objects = models.GeoManager()

    def __unicode__(self):
        return unicode(self.gridcode)


class Magallanes50Year(models.Model):
    #id = models.IntegerField()
    gridcode = models.IntegerField()
    #shape_leng = models.FloatField()
    #shape_area = models.FloatField()
    #hazard = models.CharField(max_length=30)
    geom = models.MultiPolygonField(srid=32651)
    objects = models.GeoManager()

    def __unicode__(self):
        return unicode(self.gridcode)


class Magallanes100Year(models.Model):
    #id = models.IntegerField()
    gridcode = models.IntegerField()
    #shape_leng = models.FloatField()
    #shape_area = models.FloatField()
    #hazard = models.CharField(max_length=30)
    geom = models.MultiPolygonField(srid=32651)
    objects = models.GeoManager()

    def __unicode__(self):
        return unicode(self.gridcode)


class MagallanesAgaton(models.Model):
    #id = models.IntegerField()
    gridcode = models.IntegerField()
    #shape_leng = models.FloatField()
    #shape_area = models.FloatField()
    #hazard = models.CharField(max_length=30)
    geom = models.MultiPolygonField(srid=32651)
    objects = models.GeoManager()

    def __unicode__(self):
        return unicode(self.gridcode)


class MagallanesSeniang(models.Model):
    #id = models.IntegerField()
    gridcode = models.IntegerField()
    #shape_leng = models.FloatField()
    #shape_area = models.FloatField()
    #hazard = models.CharField(max_length=30)
    geom = models.MultiPolygonField(srid=32651)
    objects = models.GeoManager()

    def __unicode__(self):
        return unicode(self.gridcode)


class SurigaoBldg(models.Model):
    #id = models.IntegerField()
    bldg_name = models.CharField(max_length=50)
    code = models.CharField(max_length=50)
    bldg_type = models.CharField(max_length=50)
    brgy_locat = models.CharField(max_length=50)
    municipali = models.CharField(max_length=50)
    province = models.CharField(max_length=50)
    geom = models.MultiPolygonField(srid=32651)
    objects = models.GeoManager()

    def __unicode__(self):
        return unicode(self.bldg_name)


class MagallanesBldg(models.Model):
    #id = models.IntegerField()
    bldg_name = models.CharField(max_length=50)
    code = models.CharField(max_length=25)
    #bldg_heigh = models.FloatField()
    bldg_type = models.CharField(max_length=50)
    brgy_locat = models.CharField(max_length=50)
    municipali = models.CharField(max_length=50)
    province = models.CharField(max_length=50)
    #source_pbo = models.CharField(max_length=50)
    geom = models.MultiPolygonField(srid=32651)
    objects = models.GeoManager()

    def __unicode__(self):
        return unicode(self.bldg_name)


#Cantilan Flood Hazard Map
class Cantilan100Year(models.Model):
    #id = models.IntegerField()
    gridcode = models.IntegerField()
    #shape_leng = models.FloatField()
    #shape_area = models.FloatField()
    #hazard = models.CharField(max_length=30)
    geom = models.MultiPolygonField(srid=32651)
    objects = models.GeoManager()

    def __unicode__(self):
        return unicode(self.gridcode)


class Cantilan50Year(models.Model):
    #id = models.IntegerField()
    gridcode = models.IntegerField()
    #shape_leng = models.FloatField()
    #shape_area = models.FloatField()
    #hazard = models.CharField(max_length=30)
    geom = models.MultiPolygonField(srid=32651)
    objects = models.GeoManager()

    def __unicode__(self):
        return unicode(self.gridcode)


class Cantilan25Year(models.Model):
    #id = models.IntegerField()
    gridcode = models.IntegerField()
    #shape_leng = models.FloatField()
    #shape_area = models.FloatField()
    #hazard = models.CharField(max_length=30)
    geom = models.MultiPolygonField(srid=32651)
    objects = models.GeoManager()

    def __unicode__(self):
        return unicode(self.gridcode)


class Cantilan10Year(models.Model):
    #id = models.IntegerField()
    gridcode = models.IntegerField()
    #shape_leng = models.FloatField()
    #shape_area = models.FloatField()
    #hazard = models.CharField(max_length=30)
    geom = models.MultiPolygonField(srid=32651)
    objects = models.GeoManager()

    def __unicode__(self):
        return unicode(self.gridcode)


class Cantilan5Year(models.Model):
    #id = models.IntegerField()
    gridcode = models.IntegerField()
    #shape_leng = models.FloatField()
    #shape_area = models.FloatField()
    #hazard = models.CharField(max_length=30)
    geom = models.MultiPolygonField(srid=32651)
    objects = models.GeoManager()

    def __unicode__(self):
        return unicode(self.gridcode)


class Cantilan2Year(models.Model):
    #id = models.IntegerField()
    gridcode = models.IntegerField()
    #shape_leng = models.FloatField()
    #shape_area = models.FloatField()
    #hazard = models.CharField(max_length=30)
    geom = models.MultiPolygonField(srid=32651)
    objects = models.GeoManager()

    def __unicode__(self):
        return unicode(self.gridcode)


class CantilanAgaton(models.Model):
    #id = models.IntegerField()
    gridcode = models.IntegerField()
    #shape_leng = models.FloatField()
    #shape_area = models.FloatField()
    #hazard = models.CharField(max_length=30)
    geom = models.MultiPolygonField(srid=32651)
    objects = models.GeoManager()

    def __unicode__(self):
        return unicode(self.gridcode)


class CantilanSeniang(models.Model):
    #id = models.IntegerField()
    gridcode = models.IntegerField()
    #shape_leng = models.FloatField()
    #shape_area = models.FloatField()
    #hazard = models.CharField(max_length=30)
    geom = models.MultiPolygonField(srid=32651)
    objects = models.GeoManager()

    def __unicode__(self):
        return unicode(self.gridcode)


class CantilanBldg(models.Model):
    #id = models.IntegerField()
    bldg_name = models.CharField(max_length=50)
    code = models.CharField(max_length=50)
    #bldg_heigh = models.FloatField()
    bldg_type = models.CharField(max_length=50)
    brgy_locat = models.CharField(max_length=50)
    municipali = models.CharField(max_length=50)
    province = models.CharField(max_length=50)
    #source_pbo = models.CharField(max_length=50)
    geom = models.MultiPolygonField(srid=32651)
    objects = models.GeoManager()

    def __unicode__(self):
        return unicode(self.bldg_name)


#### Malinao Flood Hazard Maps ####
class Malinao2Year(models.Model):
    #id = models.IntegerField()
    gridcode = models.IntegerField()
    #shape_leng = models.FloatField()
    #shape_area = models.FloatField()
    #hazard = models.CharField(max_length=30)
    geom = models.MultiPolygonField(srid=32651)
    objects = models.GeoManager()

    def __unicode__(self):
        return unicode(self.gridcode)


class Malinao5Year(models.Model):
    #id = models.IntegerField()
    gridcode = models.IntegerField()
    #shape_leng = models.FloatField()
    #shape_area = models.FloatField()
    #hazard = models.CharField(max_length=30)
    geom = models.MultiPolygonField(srid=32651)
    objects = models.GeoManager()

    def __unicode__(self):
        return unicode(self.gridcode)


class Malinao10Year(models.Model):
    #id = models.IntegerField()
    gridcode = models.IntegerField()
    #shape_leng = models.FloatField()
    #shape_area = models.FloatField()
    #hazard = models.CharField(max_length=30)
    geom = models.MultiPolygonField(srid=32651)
    objects = models.GeoManager()

    def __unicode__(self):
        return unicode(self.gridcode)


class Malinao25Year(models.Model):
    #id = models.IntegerField()
    gridcode = models.IntegerField()
    #shape_leng = models.FloatField()
    #shape_area = models.FloatField()
    #hazard = models.CharField(max_length=30)
    geom = models.MultiPolygonField(srid=32651)
    objects = models.GeoManager()

    def __unicode__(self):
        return unicode(self.gridcode)


class Malinao50Year(models.Model):
    #id = models.IntegerField()
    gridcode = models.IntegerField()
    #shape_leng = models.FloatField()
    #shape_area = models.FloatField()
    #hazard = models.CharField(max_length=30)
    geom = models.MultiPolygonField(srid=32651)
    objects = models.GeoManager()

    def __unicode__(self):
        return unicode(self.gridcode)


class Malinao100Year(models.Model):
    #id = models.IntegerField()
    gridcode = models.IntegerField()
    #shape_leng = models.FloatField()
    #shape_area = models.FloatField()
    #hazard = models.CharField(max_length=30)
    geom = models.MultiPolygonField(srid=32651)
    objects = models.GeoManager()

    def __unicode__(self):
        return unicode(self.gridcode)


class MalinaoBasyang(models.Model):
    #id = models.IntegerField()
    gridcode = models.IntegerField()
    #shape_leng = models.FloatField()
    #shape_area = models.FloatField()
    #hazard = models.CharField(max_length=30)
    geom = models.MultiPolygonField(srid=32651)
    objects = models.GeoManager()

    def __unicode__(self):
        return unicode(self.gridcode)


class MalinaoSeniang(models.Model):
    #id = models.IntegerField()
    gridcode = models.IntegerField()
    #shape_leng = models.FloatField()
    #shape_area = models.FloatField()
    #hazard = models.CharField(max_length=30)
    geom = models.MultiPolygonField(srid=32651)
    objects = models.GeoManager()

    def __unicode__(self):
        return unicode(self.gridcode)


class MalinaoBldg(models.Model):
    #id = models.IntegerField()
    bldg_name = models.CharField(max_length=50)
    code = models.CharField(max_length=50)
    #bldg_heigh = models.FloatField()
    bldg_type = models.CharField(max_length=50)
    brgy_locat = models.CharField(max_length=50)
    municipali = models.CharField(max_length=50)
    province = models.CharField(max_length=50)
    #source_pbo = models.CharField(max_length=50)
    geom = models.MultiPolygonField(srid=32651)
    objects = models.GeoManager()

    def __unicode__(self):
        return unicode(self.bldg_name)

## GAAS LULET ##
class GaasBldg(models.Model):
    #id = models.IntegerField()
    bldg_name = models.CharField(max_length=50)
    code = models.CharField(max_length=50)
    #bldg_heigh = models.FloatField()
    bldg_type = models.CharField(max_length=50)
    brgy_locat = models.CharField(max_length=50)
    municipali = models.CharField(max_length=50)
    province = models.CharField(max_length=50)
    #source_pbo = models.CharField(max_length=50)
    geom = models.MultiPolygonField(srid=32651)
    objects = models.GeoManager()

    def __unicode__(self):
        return unicode(self.bldg_name)


class Gaas2Year(models.Model):
    #id = models.IntegerField()
    gridcode = models.IntegerField()
    #shape_leng = models.FloatField()
    #shape_area = models.FloatField()
    #hazard = models.CharField(max_length=30)
    geom = models.MultiPolygonField(srid=32651)
    objects = models.GeoManager()

    def __unicode__(self):
        return unicode(self.gridcode)


class Gaas5Year(models.Model):
    #id = models.IntegerField()
    gridcode = models.IntegerField()
    #shape_leng = models.FloatField()
    #shape_area = models.FloatField()
    #hazard = models.CharField(max_length=30)
    geom = models.MultiPolygonField(srid=32651)
    objects = models.GeoManager()

    def __unicode__(self):
        return unicode(self.gridcode)


class Gaas10Year(models.Model):
    #id = models.IntegerField()
    gridcode = models.IntegerField()
    #shape_leng = models.FloatField()
    #shape_area = models.FloatField()
    #hazard = models.CharField(max_length=30)
    geom = models.MultiPolygonField(srid=32651)
    objects = models.GeoManager()

    def __unicode__(self):
        return unicode(self.gridcode)


class Gaas25Year(models.Model):
    #id = models.IntegerField()
    gridcode = models.IntegerField()
    #shape_leng = models.FloatField()
    #shape_area = models.FloatField()
    #hazard = models.CharField(max_length=30)
    geom = models.MultiPolygonField(srid=32651)
    objects = models.GeoManager()

    def __unicode__(self):
        return unicode(self.gridcode)


class Gaas50Year(models.Model):
    #id = models.IntegerField()
    gridcode = models.IntegerField()
    #shape_leng = models.FloatField()
    #shape_area = models.FloatField()
    #hazard = models.CharField(max_length=30)
    geom = models.MultiPolygonField(srid=32651)
    objects = models.GeoManager()

    def __unicode__(self):
        return unicode(self.gridcode)


class Gaas100Year(models.Model):
    #id = models.IntegerField()
    gridcode = models.IntegerField()
    #shape_leng = models.FloatField()
    #shape_area = models.FloatField()
    #hazard = models.CharField(max_length=30)
    geom = models.MultiPolygonField(srid=32651)
    objects = models.GeoManager()

    def __unicode__(self):
        return unicode(self.gridcode)


class GaasBasyang(models.Model):
    #id = models.IntegerField()
    gridcode = models.IntegerField()
    #shape_leng = models.FloatField()
    #shape_area = models.FloatField()
    #hazard = models.CharField(max_length=30)
    geom = models.MultiPolygonField(srid=32651)
    objects = models.GeoManager()

    def __unicode__(self):
        return unicode(self.gridcode)


class GaasSeniang(models.Model):
    #id = models.IntegerField()
    gridcode = models.IntegerField()
    #shape_leng = models.FloatField()
    #shape_area = models.FloatField()
    #hazard = models.CharField(max_length=30)
    geom = models.MultiPolygonField(srid=32651)
    objects = models.GeoManager()

    def __unicode__(self):
        return unicode(self.gridcode)


class TandagStats5Yr(models.Model):
    bldg_name = models.CharField(max_length=50, blank=True)
    bldg_type = models.CharField(max_length=50, blank=True)
    brgy_locat = models.CharField(max_length=50, blank=True)
    municipali = models.CharField(max_length=50, blank=True)
    gridcode = models.IntegerField(blank=True, null=True)
    geom = models.MultiPolygonField(srid=32651, blank=True, null=True)
    ct = models.BigIntegerField(blank=True, null=True)
    objects = models.GeoManager()


class FloodEventByProvince(models.Model):
    flood_event = models.CharField(max_length=100)
    stats_view = models.CharField(max_length=100)
    flood_maps = models.CharField(max_length=100)
    province = models.CharField(max_length=100)

    def __unicode__(self):
        #return "{0} {1}".format("Desc: " + unicode(self.desc), " River Basin: " + unicode(self.river_basin))
        return unicode(self.flood_event)


####VIEWS
class SurigaoDelNorteStats100Yr(models.Model):
    province = models.CharField(max_length=50, blank=True)
    municipality = models.CharField(max_length=50, blank=True)
    barangay = models.CharField(max_length=50, blank=True)
    tot_bldg = models.BigIntegerField(blank=True, null=True)
    tot_not_affect = models.BigIntegerField(blank=True, null=True)
    tot_affect = models.BigIntegerField(blank=True, null=True)
    lo = models.BigIntegerField(blank=True, null=True)
    med = models.BigIntegerField(blank=True, null=True)
    hi = models.BigIntegerField(blank=True, null=True)
    tb = models.TextField(blank=True)

    class Meta:
        managed = False
        db_table = 'surigao_del_norte_stats_100yr'


class SurigaoDelNorteStats100YrBldgtype(models.Model):
    id = models.IntegerField(blank=True, primary_key=True)
    bldg_name = models.CharField(max_length=50, blank=True)
    bldg_type = models.CharField(max_length=50, blank=True)
    brgy_locat = models.CharField(max_length=50, blank=True)
    municipali = models.CharField(max_length=50, blank=True)
    gridcode = models.IntegerField(blank=True, null=True)
    geom = models.MultiPolygonField(srid=32651, blank=True, null=True)
    ct = models.BigIntegerField(blank=True, null=True)
    objects = models.GeoManager()

    class Meta:
        managed = False
        db_table = 'surigao_del_norte_stats_100yr_bldgtype'


class SurigaoDelNorteStats10Yr(models.Model):
    province = models.CharField(max_length=50, blank=True)
    municipality = models.CharField(max_length=50, blank=True)
    barangay = models.CharField(max_length=50, blank=True)
    tot_bldg = models.BigIntegerField(blank=True, null=True)
    tot_not_affect = models.BigIntegerField(blank=True, null=True)
    tot_affect = models.BigIntegerField(blank=True, null=True)
    lo = models.BigIntegerField(blank=True, null=True)
    med = models.BigIntegerField(blank=True, null=True)
    hi = models.BigIntegerField(blank=True, null=True)
    tb = models.TextField(blank=True)

    class Meta:
        managed = False
        db_table = 'surigao_del_norte_stats_10yr'


class SurigaoDelNorteStats10YrBldgtype(models.Model):
    id = models.IntegerField(blank=True, primary_key=True)
    bldg_name = models.CharField(max_length=50, blank=True)
    bldg_type = models.CharField(max_length=50, blank=True)
    brgy_locat = models.CharField(max_length=50, blank=True)
    municipali = models.CharField(max_length=50, blank=True)
    gridcode = models.IntegerField(blank=True, null=True)
    geom = models.MultiPolygonField(srid=32651, blank=True, null=True)
    ct = models.BigIntegerField(blank=True, null=True)
    objects = models.GeoManager()

    class Meta:
        managed = False
        db_table = 'surigao_del_norte_stats_10yr_bldgtype'


class SurigaoDelNorteStats25Yr(models.Model):
    province = models.CharField(max_length=50, blank=True)
    municipality = models.CharField(max_length=50, blank=True)
    barangay = models.CharField(max_length=50, blank=True)
    tot_bldg = models.BigIntegerField(blank=True, null=True)
    tot_not_affect = models.BigIntegerField(blank=True, null=True)
    tot_affect = models.BigIntegerField(blank=True, null=True)
    lo = models.BigIntegerField(blank=True, null=True)
    med = models.BigIntegerField(blank=True, null=True)
    hi = models.BigIntegerField(blank=True, null=True)
    tb = models.TextField(blank=True)

    class Meta:
        managed = False
        db_table = 'surigao_del_norte_stats_25yr'


class SurigaoDelNorteStats25YrBldgtype(models.Model):
    id = models.IntegerField(blank=True, primary_key=True)
    bldg_name = models.CharField(max_length=50, blank=True)
    bldg_type = models.CharField(max_length=50, blank=True)
    brgy_locat = models.CharField(max_length=50, blank=True)
    municipali = models.CharField(max_length=50, blank=True)
    gridcode = models.IntegerField(blank=True, null=True)
    geom = models.MultiPolygonField(srid=32651, blank=True, null=True)
    ct = models.BigIntegerField(blank=True, null=True)
    objects = models.GeoManager()

    class Meta:
        managed = False
        db_table = 'surigao_del_norte_stats_25yr_bldgtype'


class SurigaoDelNorteStats2Yr(models.Model):
    province = models.CharField(max_length=50, blank=True)
    municipality = models.CharField(max_length=50, blank=True)
    barangay = models.CharField(max_length=50, blank=True)
    tot_bldg = models.BigIntegerField(blank=True, null=True)
    tot_not_affect = models.BigIntegerField(blank=True, null=True)
    tot_affect = models.BigIntegerField(blank=True, null=True)
    lo = models.BigIntegerField(blank=True, null=True)
    med = models.BigIntegerField(blank=True, null=True)
    hi = models.BigIntegerField(blank=True, null=True)
    tb = models.TextField(blank=True)

    class Meta:
        managed = False
        db_table = 'surigao_del_norte_stats_2yr'


class SurigaoDelNorteStats2YrBldgtype(models.Model):
    id = models.IntegerField(blank=True, primary_key=True)
    bldg_name = models.CharField(max_length=50, blank=True)
    bldg_type = models.CharField(max_length=50, blank=True)
    brgy_locat = models.CharField(max_length=50, blank=True)
    municipali = models.CharField(max_length=50, blank=True)
    gridcode = models.IntegerField(blank=True, null=True)
    geom = models.MultiPolygonField(srid=32651, blank=True, null=True)
    ct = models.BigIntegerField(blank=True, null=True)
    objects = models.GeoManager()

    class Meta:
        managed = False
        db_table = 'surigao_del_norte_stats_2yr_bldgtype'


class SurigaoDelNorteStats50Yr(models.Model):
    province = models.CharField(max_length=50, blank=True)
    municipality = models.CharField(max_length=50, blank=True)
    barangay = models.CharField(max_length=50, blank=True)
    tot_bldg = models.BigIntegerField(blank=True, null=True)
    tot_not_affect = models.BigIntegerField(blank=True, null=True)
    tot_affect = models.BigIntegerField(blank=True, null=True)
    lo = models.BigIntegerField(blank=True, null=True)
    med = models.BigIntegerField(blank=True, null=True)
    hi = models.BigIntegerField(blank=True, null=True)
    tb = models.TextField(blank=True)

    class Meta:
        managed = False
        db_table = 'surigao_del_norte_stats_50yr'


class SurigaoDelNorteStats50YrBldgtype(models.Model):
    id = models.IntegerField(blank=True, primary_key=True)
    bldg_name = models.CharField(max_length=50, blank=True)
    bldg_type = models.CharField(max_length=50, blank=True)
    brgy_locat = models.CharField(max_length=50, blank=True)
    municipali = models.CharField(max_length=50, blank=True)
    gridcode = models.IntegerField(blank=True, null=True)
    geom = models.MultiPolygonField(srid=32651, blank=True, null=True)
    ct = models.BigIntegerField(blank=True, null=True)
    objects = models.GeoManager()

    class Meta:
        managed = False
        db_table = 'surigao_del_norte_stats_50yr_bldgtype'


class SurigaoDelNorteStats5Yr(models.Model):
    province = models.CharField(max_length=50, blank=True)
    municipality = models.CharField(max_length=50, blank=True)
    barangay = models.CharField(max_length=50, blank=True)
    tot_bldg = models.BigIntegerField(blank=True, null=True)
    tot_not_affect = models.BigIntegerField(blank=True, null=True)
    tot_affect = models.BigIntegerField(blank=True, null=True)
    lo = models.BigIntegerField(blank=True, null=True)
    med = models.BigIntegerField(blank=True, null=True)
    hi = models.BigIntegerField(blank=True, null=True)
    tb = models.TextField(blank=True)

    class Meta:
        managed = False
        db_table = 'surigao_del_norte_stats_5yr'


class SurigaoDelNorteStats5YrBldgtype(models.Model):
    id = models.IntegerField(blank=True, primary_key=True)
    bldg_name = models.CharField(max_length=50, blank=True)
    bldg_type = models.CharField(max_length=50, blank=True)
    brgy_locat = models.CharField(max_length=50, blank=True)
    municipali = models.CharField(max_length=50, blank=True)
    gridcode = models.IntegerField(blank=True, null=True)
    geom = models.MultiPolygonField(srid=32651, blank=True, null=True)
    ct = models.BigIntegerField(blank=True, null=True)
    objects = models.GeoManager()

    class Meta:
        managed = False
        db_table = 'surigao_del_norte_stats_5yr_bldgtype'


class SurigaoDelNorteStatsAgaton(models.Model):
    province = models.CharField(max_length=50, blank=True)
    municipality = models.CharField(max_length=50, blank=True)
    barangay = models.CharField(max_length=50, blank=True)
    tot_bldg = models.BigIntegerField(blank=True, null=True)
    tot_not_affect = models.BigIntegerField(blank=True, null=True)
    tot_affect = models.BigIntegerField(blank=True, null=True)
    lo = models.BigIntegerField(blank=True, null=True)
    med = models.BigIntegerField(blank=True, null=True)
    hi = models.BigIntegerField(blank=True, null=True)
    tb = models.TextField(blank=True)

    class Meta:
        managed = False
        db_table = 'surigao_del_norte_stats_agaton'


class SurigaoDelNorteStatsAgatonBldgtype(models.Model):
    id = models.IntegerField(blank=True, primary_key=True)
    bldg_name = models.CharField(max_length=50, blank=True)
    bldg_type = models.CharField(max_length=50, blank=True)
    brgy_locat = models.CharField(max_length=50, blank=True)
    municipali = models.CharField(max_length=50, blank=True)
    gridcode = models.IntegerField(blank=True, null=True)
    geom = models.MultiPolygonField(srid=32651, blank=True, null=True)
    ct = models.BigIntegerField(blank=True, null=True)
    objects = models.GeoManager()

    class Meta:
        managed = False
        db_table = 'surigao_del_norte_stats_agaton_bldgtype'


class SurigaoDelNorteStatsSeniang(models.Model):
    province = models.CharField(max_length=50, blank=True)
    municipality = models.CharField(max_length=50, blank=True)
    barangay = models.CharField(max_length=50, blank=True)
    tot_bldg = models.BigIntegerField(blank=True, null=True)
    tot_not_affect = models.BigIntegerField(blank=True, null=True)
    tot_affect = models.BigIntegerField(blank=True, null=True)
    lo = models.BigIntegerField(blank=True, null=True)
    med = models.BigIntegerField(blank=True, null=True)
    hi = models.BigIntegerField(blank=True, null=True)
    tb = models.TextField(blank=True)

    class Meta:
        managed = False
        db_table = 'surigao_del_norte_stats_seniang'


class SurigaoDelNorteStatsSeniangBldgtype(models.Model):
    id = models.IntegerField(blank=True, primary_key=True)
    bldg_name = models.CharField(max_length=50, blank=True)
    bldg_type = models.CharField(max_length=50, blank=True)
    brgy_locat = models.CharField(max_length=50, blank=True)
    municipali = models.CharField(max_length=50, blank=True)
    gridcode = models.IntegerField(blank=True, null=True)
    geom = models.MultiPolygonField(srid=32651, blank=True, null=True)
    ct = models.BigIntegerField(blank=True, null=True)
    objects = models.GeoManager()

    class Meta:
        managed = False
        db_table = 'surigao_del_norte_stats_seniang_bldgtype'